### ISSUE TITLE
opkg fails to install any reMarkable-specific packages

### ISSUE THREAD

**Issue by fezzzza** [Evidlo/remarkable_entware#17]
I've tried installing entware on 2.1.1.3 (after bricking and recovering) and also on 2.9.1.236. I note during the middle of installation I get:

```
Connecting to bin.entware.net (104.21.91.83:80)
saving to '/opt/lib/libgcc_s.so.1'
libgcc_s.so.1        100% |**********************************************************************************************| 50848  0:00:00 ETA
'/opt/lib/libgcc_s.so.1' saved
Connecting to bin.entware.net (104.21.91.83:80)
saving to '/opt/lib/libpthread-2.27.so'
libpthread-2.27.so   100% |**********************************************************************************************| 92656  0:00:00 ETA
'/opt/lib/libpthread-2.27.so' saved
cat: read error: Is a directory                                           <----------------this line
pass
Downloading http://bin.entware.net/armv7sf-k3.2/Packages.gz
Updated list of available packages in /opt/var/opkg-lists/entware
Downloading https://toltec.delab.re/stable/Packages.gz
wget: note: TLS certificate validation not implemented
Updated list of available packages in /opt/var/opkg-lists/toltec
Installing entware-opt (227000-3) to root...
```
once installed, opkg does not have access to any of the apps listed at https://toltec-dev.org/stable/ 
it only has access to the packages at http://bin.entware.net/armv7sf-k3.2/
(These are the pages linked in the README.md as "See a list of available packages here and here."

**Comment by jonaustin** [comment]
I was able to fix this by adding these lines to `~/.entware/etc/opkg.conf`

```
arch rmall 200
arch rm2 300
src/gz rm2 https://toltec-dev.org/stable/rm2/
src/gz rmall https://toltec-dev.org/stable/rmall/
```

and then run `opkg update`

Note: if you have an `rm1` I assume you can just replace all instances of `rm2` above with `rm1`

My limited understanding is that the issue is 2-fold:
- It looks like toltec repo changed their repo layout; now there are subdirs and the Architecture field in packages.gz is e.g. `rm2` or `rmall`; e.g. see the previous version of the repo: https://web.archive.org/web/20210125023332/https://toltec-dev.org/stable/
- So now in order to get it to work you have to have separate sources/arch for rmall/rm1/rm2

**Comment by norandom** [comment]
Ah yes. The installer seems to be broken as well due to this. 

https://github.com/toltec-dev/toltec/issues/429#issuecomment-910607363
